blueprint:
  name: Turn off light during day
  description: Turn off light during day
  domain: automation
  source_url: https://github.com/theundefined/ha-blueprints/automation/turnoff_light_in_day.yaml
  input:
    light_entity:
      name: Light
      selector:
        entity:
          domain: light
    seconds_wait:
      name: Wait time in seconds
      description: Seconds until ligh is off
      default: 300
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input light_entity
  to: "on"
  for:
    seconds: !input seconds_wait

condition:
  - condition: sun
    before: sunset
    after: sunrise

action:
  - service: light.turn_off
    target: 
      entity_id: !input light_entity

